### PR TITLE
Adding new specifications to charter

### PR DESCRIPTION
**Pull request by igrigorik**
As Discussed on WG call on 02/08/17, adding to charter:
- Long Task API
- Paint Timing
- Element Timing API
- Memory Pressure API
- Server Timing API

### CODE REVIEW

**Comment by yoavweiss** [comment]
LGTM! Regarding Server Timing, I'm hoping to start work on use-cases doc/explainer and spec soon

**Comment by plehegar** [comment]
The "out of scope" section includes "methods to profile and instrument server side code". Is Server Timing part of that? If yes, then we need to update the out of scope section as well.

**Comment by yoavweiss** [comment]
> The "out of scope" section includes "methods to profile and instrument server side code". Is Server Timing part of that? If yes, then we need to update the out of scope section as well.

I don't think Server Timing is at odds with that scope exclusion. At most, Server Timing gives means to *report* server side profiling results to the client.

**Comment by plehegar** [comment]
One more thing: the previous charter did contain Server Timing and had the same out of scope. If we concluded at the time that Server Timing isn't prohibited by the out of scope, then no further change is needed.

**Comment by plehegar** [comment]
@yoavweiss thanks. Then no change is needed.

**Comment by plehegar** [comment]
I had further discussions with legal folks on my side about whether my past assumptions on the need for a new charter when adding new deliverables. It appears that, as long as it's within the scope section of the charter, we don't need a new charter before proceeding and I was simply incorrect to assume otherwise. As long as everyone in the Working Group agree that it's in scope, we can proceed.

**Comment by igrigorik** [comment]
@plehegar thanks, good to know. In which case, do we still want to update the charter and land these updates?

**Comment by plehegar** [comment]
Nope, no need to update the charter. You can publish the drafts as soon as you have a group decision to do so. Apologizes for my past misguidance :(

**Comment by toddreifsteck** [comment]
This LGTM. Merging.

**Pull request merged**
