### PR TITLE
Added primer and dependencies/processing model

### PR DESCRIPTION
**Pull request by plehegar**
#21

### CODE REVIEW

**Comment by igrigorik** [comment]
This commit seems to overlap with #22?

**Comment by plehegar** [comment]
@igrigorik yes, otherwise I don't think github would have been happy to merge it, so I hoped that issue-21 would accepted as well. If not, I'll align the two.

**Comment by igrigorik** [comment]
ah, fair enough. looks good.

**Comment by toddreifsteck** [comment]
Yeah. I merged the most recent commit from that branch so it was handled implicitly.

**Comment by plehegar** [comment]
Well, that didn't work actually. The commit doesn't appear in the history. I recommit that change directly...

**Comment by toddreifsteck** [comment]
Thanks for double-checking!

**Pull request merged**
